version: '3.9'

services:
  api:
    build: api
    volumes:
      - ./api:/usr/src/app
      - ./files-cloud:/files-cloud
    ports:
      - 7070:5000
      - 4000:4000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
    environment:
      FLASK_DEBUG: "on"
    
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 200M