version: '3.9'

services:
  database:
    image: postgres:15.0-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    deploy:  
      resources:
        limits:
          cpus: '0.4'
          memory: 400M

  api:
    build: api
    volumes:
      - ./api:/api
      - /api/migrations
      - /files-cloud
    ports:
      - 7070:5000
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
    environment:
      FLASK_DEBUG: "on"
    depends_on:
      database:
        condition: service_started