version: '3.9'

services:
  broker:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 100M

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    deploy:  
      resources:
        limits:
          cpus: '0.15'
          memory: 250M

  api:
    build:
      context: api
      dockerfile: minimal.Dockerfile
    volumes:
      - ./api:/api
      - /api/migrations
      - /files-cloud
    ports:
      - 7070:5000
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 600M
    environment:
      FLASK_DEBUG: "on"
    depends_on:
      database:
        condition: service_started
      broker:
        condition: service_started

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 50M